version: '3.8'  # Use the desired version of Docker Compose (adjust if needed)

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile  # Path to your server Dockerfile
    ports:
      - "8000:8000"  # Map container's port 8000 to host's port 8000

  client:
    build:
      context: .
      dockerfile: client.Dockerfile  # Path to your client Dockerfile
    ports:
      - "3000:3000"  # Map container's port 3000 to host's port 3000